/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualHarnessRouteImport } from './routes/visual-harness'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalariesRouteImport } from './routes/salaries'
import { Route as InterviewPrepRouteImport } from './routes/interview-prep'
import { Route as ExternalLinkRouteImport } from './routes/external-link'
import { Route as CareerAdviceRouteImport } from './routes/career-advice'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InterviewPrepMockRouteImport } from './routes/interview-prep.mock'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as CareerAdviceNgoJobsRouteImport } from './routes/career-advice.ngo-jobs'
import { Route as AuthenticatedMyApplicationsRouteImport } from './routes/_authenticated/my-applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCvParserRouteImport } from './routes/_authenticated/cv-parser'
import { Route as AuthenticatedCvBuilderRouteImport } from './routes/_authenticated/cv-builder'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedEmployerRouteRouteImport } from './routes/_authenticated/employer/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn/index'
import { Route as AuthenticatedInterviewIndexRouteImport } from './routes/_authenticated/interview/index'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs.$jobId.apply'
import { Route as JobsJobIdAppliedRouteImport } from './routes/jobs.$jobId.applied'
import { Route as AuthenticatedMyApplicationsAppIdRouteImport } from './routes/_authenticated/my-applications.$appId'
import { Route as AuthenticatedLearnExamPrepRouteImport } from './routes/_authenticated/learn/exam-prep'
import { Route as AuthenticatedInterviewSetupRouteImport } from './routes/_authenticated/interview/setup'
import { Route as AuthenticatedInterviewHistoryRouteImport } from './routes/_authenticated/interview/history'
import { Route as AuthenticatedEmployerJobsRouteImport } from './routes/_authenticated/employer/jobs'
import { Route as AuthenticatedEmployerDashboardRouteImport } from './routes/_authenticated/employer/dashboard'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer/company'
import { Route as AuthenticatedEmployerApplicantsRouteImport } from './routes/_authenticated/employer/applicants'
import { Route as AuthenticatedAppointmentLetterIdRouteImport } from './routes/_authenticated/appointment.$letterId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminModulesRouteImport } from './routes/_authenticated/admin/modules'
import { Route as AuthenticatedAdminLettersRouteImport } from './routes/_authenticated/admin/letters'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminInterviewsRouteImport } from './routes/_authenticated/admin/interviews'
import { Route as AuthenticatedAdminEmployersRouteImport } from './routes/_authenticated/admin/employers'
import { Route as AuthenticatedAdminDatabaseRouteImport } from './routes/_authenticated/admin/database'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCredentialsRouteImport } from './routes/_authenticated/admin/credentials'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin/applications'
import { Route as ApiPublicHooksSyncExternalJobsRouteImport } from './routes/api/public/hooks/sync-external-jobs'
import { Route as AuthenticatedLearnDisciplineTopicRouteImport } from './routes/_authenticated/learn/$discipline.$topic'
import { Route as AuthenticatedInterviewSessionSessionIdRouteImport } from './routes/_authenticated/interview/session.$sessionId'
import { Route as AuthenticatedInterviewResultSessionIdRouteImport } from './routes/_authenticated/interview/result.$sessionId'
import { Route as AuthenticatedEmployerApplicantsAppIdRouteImport } from './routes/_authenticated/employer/applicants.$appId'

const VisualHarnessRoute = VisualHarnessRouteImport.update({
  id: '/visual-harness',
  path: '/visual-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesRoute = SalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPrepRoute = InterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalLinkRoute = ExternalLinkRouteImport.update({
  id: '/external-link',
  path: '/external-link',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerAdviceRoute = CareerAdviceRouteImport.update({
  id: '/career-advice',
  path: '/career-advice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPrepMockRoute = InterviewPrepMockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => InterviewPrepRoute,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerAdviceNgoJobsRoute = CareerAdviceNgoJobsRouteImport.update({
  id: '/ngo-jobs',
  path: '/ngo-jobs',
  getParentRoute: () => CareerAdviceRoute,
} as any)
const AuthenticatedMyApplicationsRoute =
  AuthenticatedMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvParserRoute = AuthenticatedCvParserRouteImport.update({
  id: '/cv-parser',
  path: '/cv-parser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvBuilderRoute = AuthenticatedCvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerRouteRoute =
  AuthenticatedEmployerRouteRouteImport.update({
    id: '/employer',
    path: '/employer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewIndexRoute =
  AuthenticatedInterviewIndexRouteImport.update({
    id: '/interview/',
    path: '/interview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdAppliedRoute = JobsJobIdAppliedRouteImport.update({
  id: '/applied',
  path: '/applied',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const AuthenticatedMyApplicationsAppIdRoute =
  AuthenticatedMyApplicationsAppIdRouteImport.update({
    id: '/$appId',
    path: '/$appId',
    getParentRoute: () => AuthenticatedMyApplicationsRoute,
  } as any)
const AuthenticatedLearnExamPrepRoute =
  AuthenticatedLearnExamPrepRouteImport.update({
    id: '/learn/exam-prep',
    path: '/learn/exam-prep',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewSetupRoute =
  AuthenticatedInterviewSetupRouteImport.update({
    id: '/interview/setup',
    path: '/interview/setup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewHistoryRoute =
  AuthenticatedInterviewHistoryRouteImport.update({
    id: '/interview/history',
    path: '/interview/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsRoute =
  AuthenticatedEmployerJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerDashboardRoute =
  AuthenticatedEmployerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerApplicantsRoute =
  AuthenticatedEmployerApplicantsRouteImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedAppointmentLetterIdRoute =
  AuthenticatedAppointmentLetterIdRouteImport.update({
    id: '/appointment/$letterId',
    path: '/appointment/$letterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminModulesRoute =
  AuthenticatedAdminModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLettersRoute =
  AuthenticatedAdminLettersRouteImport.update({
    id: '/letters',
    path: '/letters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInterviewsRoute =
  AuthenticatedAdminInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmployersRoute =
  AuthenticatedAdminEmployersRouteImport.update({
    id: '/employers',
    path: '/employers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDatabaseRoute =
  AuthenticatedAdminDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCredentialsRoute =
  AuthenticatedAdminCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicHooksSyncExternalJobsRoute =
  ApiPublicHooksSyncExternalJobsRouteImport.update({
    id: '/api/public/hooks/sync-external-jobs',
    path: '/api/public/hooks/sync-external-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLearnDisciplineTopicRoute =
  AuthenticatedLearnDisciplineTopicRouteImport.update({
    id: '/learn/$discipline/$topic',
    path: '/learn/$discipline/$topic',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewSessionSessionIdRoute =
  AuthenticatedInterviewSessionSessionIdRouteImport.update({
    id: '/interview/session/$sessionId',
    path: '/interview/session/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewResultSessionIdRoute =
  AuthenticatedInterviewResultSessionIdRouteImport.update({
    id: '/interview/result/$sessionId',
    path: '/interview/result/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerApplicantsAppIdRoute =
  AuthenticatedEmployerApplicantsAppIdRouteImport.update({
    id: '/$appId',
    path: '/$appId',
    getParentRoute: () => AuthenticatedEmployerApplicantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-advice': typeof CareerAdviceRouteWithChildren
  '/external-link': typeof ExternalLinkRoute
  '/interview-prep': typeof InterviewPrepRouteWithChildren
  '/salaries': typeof SalariesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visual-harness': typeof VisualHarnessRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/employer': typeof AuthenticatedEmployerRouteRouteWithChildren
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/cv-parser': typeof AuthenticatedCvParserRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRouteWithChildren
  '/career-advice/ngo-jobs': typeof CareerAdviceNgoJobsRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/interview-prep/mock': typeof InterviewPrepMockRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/appointment/$letterId': typeof AuthenticatedAppointmentLetterIdRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRouteWithChildren
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/interview/history': typeof AuthenticatedInterviewHistoryRoute
  '/interview/setup': typeof AuthenticatedInterviewSetupRoute
  '/learn/exam-prep': typeof AuthenticatedLearnExamPrepRoute
  '/my-applications/$appId': typeof AuthenticatedMyApplicationsAppIdRoute
  '/jobs/$jobId/applied': typeof JobsJobIdAppliedRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/interview/': typeof AuthenticatedInterviewIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/employer/applicants/$appId': typeof AuthenticatedEmployerApplicantsAppIdRoute
  '/interview/result/$sessionId': typeof AuthenticatedInterviewResultSessionIdRoute
  '/interview/session/$sessionId': typeof AuthenticatedInterviewSessionSessionIdRoute
  '/learn/$discipline/$topic': typeof AuthenticatedLearnDisciplineTopicRoute
  '/api/public/hooks/sync-external-jobs': typeof ApiPublicHooksSyncExternalJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-advice': typeof CareerAdviceRouteWithChildren
  '/external-link': typeof ExternalLinkRoute
  '/interview-prep': typeof InterviewPrepRouteWithChildren
  '/salaries': typeof SalariesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visual-harness': typeof VisualHarnessRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/employer': typeof AuthenticatedEmployerRouteRouteWithChildren
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/cv-parser': typeof AuthenticatedCvParserRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRouteWithChildren
  '/career-advice/ngo-jobs': typeof CareerAdviceNgoJobsRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/interview-prep/mock': typeof InterviewPrepMockRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/companies': typeof CompaniesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/appointment/$letterId': typeof AuthenticatedAppointmentLetterIdRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRouteWithChildren
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/interview/history': typeof AuthenticatedInterviewHistoryRoute
  '/interview/setup': typeof AuthenticatedInterviewSetupRoute
  '/learn/exam-prep': typeof AuthenticatedLearnExamPrepRoute
  '/my-applications/$appId': typeof AuthenticatedMyApplicationsAppIdRoute
  '/jobs/$jobId/applied': typeof JobsJobIdAppliedRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/interview': typeof AuthenticatedInterviewIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/employer/applicants/$appId': typeof AuthenticatedEmployerApplicantsAppIdRoute
  '/interview/result/$sessionId': typeof AuthenticatedInterviewResultSessionIdRoute
  '/interview/session/$sessionId': typeof AuthenticatedInterviewSessionSessionIdRoute
  '/learn/$discipline/$topic': typeof AuthenticatedLearnDisciplineTopicRoute
  '/api/public/hooks/sync-external-jobs': typeof ApiPublicHooksSyncExternalJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/career-advice': typeof CareerAdviceRouteWithChildren
  '/external-link': typeof ExternalLinkRoute
  '/interview-prep': typeof InterviewPrepRouteWithChildren
  '/salaries': typeof SalariesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visual-harness': typeof VisualHarnessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteRouteWithChildren
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/_authenticated/cv-parser': typeof AuthenticatedCvParserRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-applications': typeof AuthenticatedMyApplicationsRouteWithChildren
  '/career-advice/ngo-jobs': typeof CareerAdviceNgoJobsRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/interview-prep/mock': typeof InterviewPrepMockRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/_authenticated/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/_authenticated/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/_authenticated/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/appointment/$letterId': typeof AuthenticatedAppointmentLetterIdRoute
  '/_authenticated/employer/applicants': typeof AuthenticatedEmployerApplicantsRouteWithChildren
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/_authenticated/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/_authenticated/interview/history': typeof AuthenticatedInterviewHistoryRoute
  '/_authenticated/interview/setup': typeof AuthenticatedInterviewSetupRoute
  '/_authenticated/learn/exam-prep': typeof AuthenticatedLearnExamPrepRoute
  '/_authenticated/my-applications/$appId': typeof AuthenticatedMyApplicationsAppIdRoute
  '/jobs/$jobId/applied': typeof JobsJobIdAppliedRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/_authenticated/interview/': typeof AuthenticatedInterviewIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/employer/applicants/$appId': typeof AuthenticatedEmployerApplicantsAppIdRoute
  '/_authenticated/interview/result/$sessionId': typeof AuthenticatedInterviewResultSessionIdRoute
  '/_authenticated/interview/session/$sessionId': typeof AuthenticatedInterviewSessionSessionIdRoute
  '/_authenticated/learn/$discipline/$topic': typeof AuthenticatedLearnDisciplineTopicRoute
  '/api/public/hooks/sync-external-jobs': typeof ApiPublicHooksSyncExternalJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/career-advice'
    | '/external-link'
    | '/interview-prep'
    | '/salaries'
    | '/sitemap.xml'
    | '/visual-harness'
    | '/admin'
    | '/employer'
    | '/assessments'
    | '/cv-builder'
    | '/cv-parser'
    | '/dashboard'
    | '/my-applications'
    | '/career-advice/ngo-jobs'
    | '/companies/$slug'
    | '/interview-prep/mock'
    | '/jobs/$jobId'
    | '/companies/'
    | '/jobs/'
    | '/admin/applications'
    | '/admin/companies'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/database'
    | '/admin/employers'
    | '/admin/interviews'
    | '/admin/jobs'
    | '/admin/letters'
    | '/admin/modules'
    | '/admin/users'
    | '/appointment/$letterId'
    | '/employer/applicants'
    | '/employer/company'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/interview/history'
    | '/interview/setup'
    | '/learn/exam-prep'
    | '/my-applications/$appId'
    | '/jobs/$jobId/applied'
    | '/jobs/$jobId/apply'
    | '/interview/'
    | '/learn/'
    | '/employer/applicants/$appId'
    | '/interview/result/$sessionId'
    | '/interview/session/$sessionId'
    | '/learn/$discipline/$topic'
    | '/api/public/hooks/sync-external-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/career-advice'
    | '/external-link'
    | '/interview-prep'
    | '/salaries'
    | '/sitemap.xml'
    | '/visual-harness'
    | '/admin'
    | '/employer'
    | '/assessments'
    | '/cv-builder'
    | '/cv-parser'
    | '/dashboard'
    | '/my-applications'
    | '/career-advice/ngo-jobs'
    | '/companies/$slug'
    | '/interview-prep/mock'
    | '/jobs/$jobId'
    | '/companies'
    | '/jobs'
    | '/admin/applications'
    | '/admin/companies'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/database'
    | '/admin/employers'
    | '/admin/interviews'
    | '/admin/jobs'
    | '/admin/letters'
    | '/admin/modules'
    | '/admin/users'
    | '/appointment/$letterId'
    | '/employer/applicants'
    | '/employer/company'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/interview/history'
    | '/interview/setup'
    | '/learn/exam-prep'
    | '/my-applications/$appId'
    | '/jobs/$jobId/applied'
    | '/jobs/$jobId/apply'
    | '/interview'
    | '/learn'
    | '/employer/applicants/$appId'
    | '/interview/result/$sessionId'
    | '/interview/session/$sessionId'
    | '/learn/$discipline/$topic'
    | '/api/public/hooks/sync-external-jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/career-advice'
    | '/external-link'
    | '/interview-prep'
    | '/salaries'
    | '/sitemap.xml'
    | '/visual-harness'
    | '/_authenticated/admin'
    | '/_authenticated/employer'
    | '/_authenticated/assessments'
    | '/_authenticated/cv-builder'
    | '/_authenticated/cv-parser'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-applications'
    | '/career-advice/ngo-jobs'
    | '/companies/$slug'
    | '/interview-prep/mock'
    | '/jobs/$jobId'
    | '/companies/'
    | '/jobs/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/credentials'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/database'
    | '/_authenticated/admin/employers'
    | '/_authenticated/admin/interviews'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/letters'
    | '/_authenticated/admin/modules'
    | '/_authenticated/admin/users'
    | '/_authenticated/appointment/$letterId'
    | '/_authenticated/employer/applicants'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/dashboard'
    | '/_authenticated/employer/jobs'
    | '/_authenticated/interview/history'
    | '/_authenticated/interview/setup'
    | '/_authenticated/learn/exam-prep'
    | '/_authenticated/my-applications/$appId'
    | '/jobs/$jobId/applied'
    | '/jobs/$jobId/apply'
    | '/_authenticated/interview/'
    | '/_authenticated/learn/'
    | '/_authenticated/employer/applicants/$appId'
    | '/_authenticated/interview/result/$sessionId'
    | '/_authenticated/interview/session/$sessionId'
    | '/_authenticated/learn/$discipline/$topic'
    | '/api/public/hooks/sync-external-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareerAdviceRoute: typeof CareerAdviceRouteWithChildren
  ExternalLinkRoute: typeof ExternalLinkRoute
  InterviewPrepRoute: typeof InterviewPrepRouteWithChildren
  SalariesRoute: typeof SalariesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisualHarnessRoute: typeof VisualHarnessRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiPublicHooksSyncExternalJobsRoute: typeof ApiPublicHooksSyncExternalJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual-harness': {
      id: '/visual-harness'
      path: '/visual-harness'
      fullPath: '/visual-harness'
      preLoaderRoute: typeof VisualHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries': {
      id: '/salaries'
      path: '/salaries'
      fullPath: '/salaries'
      preLoaderRoute: typeof SalariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-prep': {
      id: '/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof InterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-link': {
      id: '/external-link'
      path: '/external-link'
      fullPath: '/external-link'
      preLoaderRoute: typeof ExternalLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-advice': {
      id: '/career-advice'
      path: '/career-advice'
      fullPath: '/career-advice'
      preLoaderRoute: typeof CareerAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-prep/mock': {
      id: '/interview-prep/mock'
      path: '/mock'
      fullPath: '/interview-prep/mock'
      preLoaderRoute: typeof InterviewPrepMockRouteImport
      parentRoute: typeof InterviewPrepRoute
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-advice/ngo-jobs': {
      id: '/career-advice/ngo-jobs'
      path: '/ngo-jobs'
      fullPath: '/career-advice/ngo-jobs'
      preLoaderRoute: typeof CareerAdviceNgoJobsRouteImport
      parentRoute: typeof CareerAdviceRoute
    }
    '/_authenticated/my-applications': {
      id: '/_authenticated/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof AuthenticatedMyApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv-parser': {
      id: '/_authenticated/cv-parser'
      path: '/cv-parser'
      fullPath: '/cv-parser'
      preLoaderRoute: typeof AuthenticatedCvParserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv-builder': {
      id: '/_authenticated/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof AuthenticatedCvBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/': {
      id: '/_authenticated/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof AuthenticatedInterviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/applied': {
      id: '/jobs/$jobId/applied'
      path: '/applied'
      fullPath: '/jobs/$jobId/applied'
      preLoaderRoute: typeof JobsJobIdAppliedRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/_authenticated/my-applications/$appId': {
      id: '/_authenticated/my-applications/$appId'
      path: '/$appId'
      fullPath: '/my-applications/$appId'
      preLoaderRoute: typeof AuthenticatedMyApplicationsAppIdRouteImport
      parentRoute: typeof AuthenticatedMyApplicationsRoute
    }
    '/_authenticated/learn/exam-prep': {
      id: '/_authenticated/learn/exam-prep'
      path: '/learn/exam-prep'
      fullPath: '/learn/exam-prep'
      preLoaderRoute: typeof AuthenticatedLearnExamPrepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/setup': {
      id: '/_authenticated/interview/setup'
      path: '/interview/setup'
      fullPath: '/interview/setup'
      preLoaderRoute: typeof AuthenticatedInterviewSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/history': {
      id: '/_authenticated/interview/history'
      path: '/interview/history'
      fullPath: '/interview/history'
      preLoaderRoute: typeof AuthenticatedInterviewHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs': {
      id: '/_authenticated/employer/jobs'
      path: '/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof AuthenticatedEmployerJobsRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/dashboard': {
      id: '/_authenticated/employer/dashboard'
      path: '/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof AuthenticatedEmployerDashboardRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/applicants': {
      id: '/_authenticated/employer/applicants'
      path: '/applicants'
      fullPath: '/employer/applicants'
      preLoaderRoute: typeof AuthenticatedEmployerApplicantsRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/appointment/$letterId': {
      id: '/_authenticated/appointment/$letterId'
      path: '/appointment/$letterId'
      fullPath: '/appointment/$letterId'
      preLoaderRoute: typeof AuthenticatedAppointmentLetterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modules': {
      id: '/_authenticated/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/letters': {
      id: '/_authenticated/admin/letters'
      path: '/letters'
      fullPath: '/admin/letters'
      preLoaderRoute: typeof AuthenticatedAdminLettersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/interviews': {
      id: '/_authenticated/admin/interviews'
      path: '/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AuthenticatedAdminInterviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/employers': {
      id: '/_authenticated/admin/employers'
      path: '/employers'
      fullPath: '/admin/employers'
      preLoaderRoute: typeof AuthenticatedAdminEmployersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/database': {
      id: '/_authenticated/admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AuthenticatedAdminDatabaseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/credentials': {
      id: '/_authenticated/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthenticatedAdminCredentialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/sync-external-jobs': {
      id: '/api/public/hooks/sync-external-jobs'
      path: '/api/public/hooks/sync-external-jobs'
      fullPath: '/api/public/hooks/sync-external-jobs'
      preLoaderRoute: typeof ApiPublicHooksSyncExternalJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn/$discipline/$topic': {
      id: '/_authenticated/learn/$discipline/$topic'
      path: '/learn/$discipline/$topic'
      fullPath: '/learn/$discipline/$topic'
      preLoaderRoute: typeof AuthenticatedLearnDisciplineTopicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/session/$sessionId': {
      id: '/_authenticated/interview/session/$sessionId'
      path: '/interview/session/$sessionId'
      fullPath: '/interview/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedInterviewSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/result/$sessionId': {
      id: '/_authenticated/interview/result/$sessionId'
      path: '/interview/result/$sessionId'
      fullPath: '/interview/result/$sessionId'
      preLoaderRoute: typeof AuthenticatedInterviewResultSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/applicants/$appId': {
      id: '/_authenticated/employer/applicants/$appId'
      path: '/$appId'
      fullPath: '/employer/applicants/$appId'
      preLoaderRoute: typeof AuthenticatedEmployerApplicantsAppIdRouteImport
      parentRoute: typeof AuthenticatedEmployerApplicantsRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminCredentialsRoute: typeof AuthenticatedAdminCredentialsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDatabaseRoute: typeof AuthenticatedAdminDatabaseRoute
  AuthenticatedAdminEmployersRoute: typeof AuthenticatedAdminEmployersRoute
  AuthenticatedAdminInterviewsRoute: typeof AuthenticatedAdminInterviewsRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminLettersRoute: typeof AuthenticatedAdminLettersRoute
  AuthenticatedAdminModulesRoute: typeof AuthenticatedAdminModulesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
    AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
    AuthenticatedAdminCredentialsRoute: AuthenticatedAdminCredentialsRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminDatabaseRoute: AuthenticatedAdminDatabaseRoute,
    AuthenticatedAdminEmployersRoute: AuthenticatedAdminEmployersRoute,
    AuthenticatedAdminInterviewsRoute: AuthenticatedAdminInterviewsRoute,
    AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
    AuthenticatedAdminLettersRoute: AuthenticatedAdminLettersRoute,
    AuthenticatedAdminModulesRoute: AuthenticatedAdminModulesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedEmployerApplicantsRouteChildren {
  AuthenticatedEmployerApplicantsAppIdRoute: typeof AuthenticatedEmployerApplicantsAppIdRoute
}

const AuthenticatedEmployerApplicantsRouteChildren: AuthenticatedEmployerApplicantsRouteChildren =
  {
    AuthenticatedEmployerApplicantsAppIdRoute:
      AuthenticatedEmployerApplicantsAppIdRoute,
  }

const AuthenticatedEmployerApplicantsRouteWithChildren =
  AuthenticatedEmployerApplicantsRoute._addFileChildren(
    AuthenticatedEmployerApplicantsRouteChildren,
  )

interface AuthenticatedEmployerRouteRouteChildren {
  AuthenticatedEmployerApplicantsRoute: typeof AuthenticatedEmployerApplicantsRouteWithChildren
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerDashboardRoute: typeof AuthenticatedEmployerDashboardRoute
  AuthenticatedEmployerJobsRoute: typeof AuthenticatedEmployerJobsRoute
}

const AuthenticatedEmployerRouteRouteChildren: AuthenticatedEmployerRouteRouteChildren =
  {
    AuthenticatedEmployerApplicantsRoute:
      AuthenticatedEmployerApplicantsRouteWithChildren,
    AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
    AuthenticatedEmployerDashboardRoute: AuthenticatedEmployerDashboardRoute,
    AuthenticatedEmployerJobsRoute: AuthenticatedEmployerJobsRoute,
  }

const AuthenticatedEmployerRouteRouteWithChildren =
  AuthenticatedEmployerRouteRoute._addFileChildren(
    AuthenticatedEmployerRouteRouteChildren,
  )

interface AuthenticatedMyApplicationsRouteChildren {
  AuthenticatedMyApplicationsAppIdRoute: typeof AuthenticatedMyApplicationsAppIdRoute
}

const AuthenticatedMyApplicationsRouteChildren: AuthenticatedMyApplicationsRouteChildren =
  {
    AuthenticatedMyApplicationsAppIdRoute:
      AuthenticatedMyApplicationsAppIdRoute,
  }

const AuthenticatedMyApplicationsRouteWithChildren =
  AuthenticatedMyApplicationsRoute._addFileChildren(
    AuthenticatedMyApplicationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedEmployerRouteRoute: typeof AuthenticatedEmployerRouteRouteWithChildren
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedCvBuilderRoute: typeof AuthenticatedCvBuilderRoute
  AuthenticatedCvParserRoute: typeof AuthenticatedCvParserRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyApplicationsRoute: typeof AuthenticatedMyApplicationsRouteWithChildren
  AuthenticatedAppointmentLetterIdRoute: typeof AuthenticatedAppointmentLetterIdRoute
  AuthenticatedInterviewHistoryRoute: typeof AuthenticatedInterviewHistoryRoute
  AuthenticatedInterviewSetupRoute: typeof AuthenticatedInterviewSetupRoute
  AuthenticatedLearnExamPrepRoute: typeof AuthenticatedLearnExamPrepRoute
  AuthenticatedInterviewIndexRoute: typeof AuthenticatedInterviewIndexRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
  AuthenticatedInterviewResultSessionIdRoute: typeof AuthenticatedInterviewResultSessionIdRoute
  AuthenticatedInterviewSessionSessionIdRoute: typeof AuthenticatedInterviewSessionSessionIdRoute
  AuthenticatedLearnDisciplineTopicRoute: typeof AuthenticatedLearnDisciplineTopicRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedEmployerRouteRoute: AuthenticatedEmployerRouteRouteWithChildren,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedCvBuilderRoute: AuthenticatedCvBuilderRoute,
  AuthenticatedCvParserRoute: AuthenticatedCvParserRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyApplicationsRoute:
    AuthenticatedMyApplicationsRouteWithChildren,
  AuthenticatedAppointmentLetterIdRoute: AuthenticatedAppointmentLetterIdRoute,
  AuthenticatedInterviewHistoryRoute: AuthenticatedInterviewHistoryRoute,
  AuthenticatedInterviewSetupRoute: AuthenticatedInterviewSetupRoute,
  AuthenticatedLearnExamPrepRoute: AuthenticatedLearnExamPrepRoute,
  AuthenticatedInterviewIndexRoute: AuthenticatedInterviewIndexRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
  AuthenticatedInterviewResultSessionIdRoute:
    AuthenticatedInterviewResultSessionIdRoute,
  AuthenticatedInterviewSessionSessionIdRoute:
    AuthenticatedInterviewSessionSessionIdRoute,
  AuthenticatedLearnDisciplineTopicRoute:
    AuthenticatedLearnDisciplineTopicRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CareerAdviceRouteChildren {
  CareerAdviceNgoJobsRoute: typeof CareerAdviceNgoJobsRoute
}

const CareerAdviceRouteChildren: CareerAdviceRouteChildren = {
  CareerAdviceNgoJobsRoute: CareerAdviceNgoJobsRoute,
}

const CareerAdviceRouteWithChildren = CareerAdviceRoute._addFileChildren(
  CareerAdviceRouteChildren,
)

interface InterviewPrepRouteChildren {
  InterviewPrepMockRoute: typeof InterviewPrepMockRoute
}

const InterviewPrepRouteChildren: InterviewPrepRouteChildren = {
  InterviewPrepMockRoute: InterviewPrepMockRoute,
}

const InterviewPrepRouteWithChildren = InterviewPrepRoute._addFileChildren(
  InterviewPrepRouteChildren,
)

interface JobsJobIdRouteChildren {
  JobsJobIdAppliedRoute: typeof JobsJobIdAppliedRoute
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdAppliedRoute: JobsJobIdAppliedRoute,
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CareerAdviceRoute: CareerAdviceRouteWithChildren,
  ExternalLinkRoute: ExternalLinkRoute,
  InterviewPrepRoute: InterviewPrepRouteWithChildren,
  SalariesRoute: SalariesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisualHarnessRoute: VisualHarnessRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  CompaniesIndexRoute: CompaniesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiPublicHooksSyncExternalJobsRoute: ApiPublicHooksSyncExternalJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
