-- Additional CSE learning modules with videos, docs, and resources.
INSERT INTO public.learning_modules (discipline, section_slug, title, description, documentation_body, video_url, documentation_url, resources) VALUES
('cse','operating-systems','Operating Systems','Processes, threads, scheduling, memory management, and file systems.','# Operating Systems\n\nUnderstand how modern OS kernels manage CPU, memory, storage, and devices. Covers processes vs threads, scheduling algorithms, virtual memory, concurrency primitives, and file systems.','https://www.youtube.com/watch?v=26QPDBe-NB8','https://pages.cs.wisc.edu/~remzi/OSTEP/', '[{"type":"doc","label":"OSTEP (free textbook)","url":"https://pages.cs.wisc.edu/~remzi/OSTEP/"},{"type":"doc","label":"MIT 6.828 OS course","url":"https://pcs.csail.mit.edu/6.828/"}]'::jsonb),
('cse','system-design','System Design','Design scalable, reliable, real-world systems used by top tech firms.','# System Design\n\nLearn to design large-scale services: load balancing, caching, sharding, replication, queues, CAP theorem, and consistent hashing. Practice with URL shortener, chat, and news feed designs.','https://www.youtube.com/watch?v=MbjObHmDbZo','https://github.com/donnemartin/system-design-primer', '[{"type":"doc","label":"System Design Primer (GitHub)","url":"https://github.com/donnemartin/system-design-primer"},{"type":"doc","label":"High Scalability blog","url":"http://highscalability.com/"}]'::jsonb),
('cse','machine-learning','Machine Learning','Supervised, unsupervised, and deep learning with Python and scikit-learn.','# Machine Learning\n\nLinear/logistic regression, decision trees, SVMs, clustering, and neural networks. Learn to train, evaluate, and deploy models with scikit-learn and PyTorch.','https://www.youtube.com/watch?v=i_LwzRVP7bg','https://scikit-learn.org/stable/user_guide.html', '[{"type":"doc","label":"scikit-learn user guide","url":"https://scikit-learn.org/stable/user_guide.html"},{"type":"doc","label":"Andrew Ng ML course notes","url":"https://cs229.stanford.edu/"}]'::jsonb),
('cse','cybersecurity','Cybersecurity Essentials','Web security, cryptography basics, and secure coding practices.','# Cybersecurity\n\nOWASP Top 10, authentication, TLS, hashing, XSS, SQLi, CSRF, secure headers, and threat modelling for modern web apps.','https://www.youtube.com/watch?v=U_P23SqJaDc','https://owasp.org/www-project-top-ten/', '[{"type":"doc","label":"OWASP Top 10","url":"https://owasp.org/www-project-top-ten/"},{"type":"doc","label":"PortSwigger Web Security Academy","url":"https://portswigger.net/web-security"}]'::jsonb),
('cse','cloud-devops','Cloud & DevOps','Docker, Kubernetes, CI/CD, and cloud deployment on AWS/GCP.','# Cloud & DevOps\n\nContainerize apps with Docker, orchestrate with Kubernetes, automate delivery with GitHub Actions, and deploy to AWS/GCP/Cloudflare.','https://www.youtube.com/watch?v=3c-iBn73dDE','https://kubernetes.io/docs/home/', '[{"type":"doc","label":"Kubernetes docs","url":"https://kubernetes.io/docs/home/"},{"type":"doc","label":"Docker docs","url":"https://docs.docker.com/"},{"type":"doc","label":"AWS Well-Architected","url":"https://aws.amazon.com/architecture/well-architected/"}]'::jsonb),
('cse','git-github','Git & GitHub','Version control workflows, branching strategies, and open source collaboration.','# Git & GitHub\n\nMaster git commit/branch/merge/rebase, GitHub PR workflows, code review, and CI/CD integration.','https://www.youtube.com/watch?v=RGOj5yH7evk','https://git-scm.com/book/en/v2', '[{"type":"doc","label":"Pro Git (free book)","url":"https://git-scm.com/book/en/v2"},{"type":"doc","label":"GitHub Docs","url":"https://docs.github.com/"}]'::jsonb),
('cse','oop','Object-Oriented Programming','Classes, inheritance, polymorphism, and SOLID design principles.','# OOP\n\nCore OOP pillars — encapsulation, inheritance, polymorphism, abstraction — with Java/Python/C++ examples. Then SOLID principles and common design patterns.','https://www.youtube.com/watch?v=pTB0EiLXUC8','https://refactoring.guru/design-patterns', '[{"type":"doc","label":"Refactoring.Guru design patterns","url":"https://refactoring.guru/design-patterns"},{"type":"doc","label":"SOLID principles explained","url":"https://en.wikipedia.org/wiki/SOLID"}]'::jsonb),
('cse','competitive-programming','Competitive Programming','Problem-solving patterns, contests, and interview-grade algorithm practice.','# Competitive Programming\n\nGreedy, DP, graph algorithms, number theory, and sliding window. Practice on Codeforces, LeetCode, and AtCoder.','https://www.youtube.com/watch?v=xAeiXy8-9Y8','https://cp-algorithms.com/', '[{"type":"doc","label":"CP-Algorithms","url":"https://cp-algorithms.com/"},{"type":"doc","label":"LeetCode","url":"https://leetcode.com/"},{"type":"doc","label":"Codeforces","url":"https://codeforces.com/"}]'::jsonb)
ON CONFLICT (discipline, section_slug) DO NOTHING;
